### ISSUE TITLE
Any chance to use adjust tag in google tag manager?

### ISSUE THREAD

**Issue by alextorn** [adjust/web_sdk#12]
Hey folks,

Is there any chance to integrate adjust with a google tag manager (GTM) on the web?

Thanks

**Comment by YaraMatkova** [comment]
Hey @liamtarpey, thank you for reaching out.

I think you could get a more detailed answer if you contact your Adjust Account Manager or Customer Success Manager.

As far as I aware there is no special elegant solution to make Web SDK events work with GTM, and most likely you have to use Custom JS scripts but you could trigger them on on built-in GTM events.

Feel free to comment if you have any further questions.
