### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by IsaacGluck** [adjust/web_sdk#14]
Would be great if the web_sdk had Typescript support. It's already in the react native sdk: [https://github.com/adjust/react_native_sdk/blob/master/index.d.ts](https://github.com/adjust/react_native_sdk/blob/master/index.d.ts)

Thanks!

**Comment by YaroslavnaMatkova** [comment]
Hi @IsaacGluck! Thanks for reaching out to us. We are going to add Typescript support in the next SDK update.
