### ISSUE TITLE
web sdk not working

### ISSUE THREAD

**Issue by sanjosedennis7593** [adjust/web_sdk#18]
Hi,

I just want to raise an issue with your web SDK , and I have been followed the instruction you provided carefully. 

Every time this code trigger inside a click event handler.

Adjust.trackEvent({
  eventToken: 'YOUR_EVENT_TOKEN'
});

There something in the logs states "Running track event is delayed until Adjust SDK is up".

No idea why this shown up, I have been initialized the SDK before mounting the root component. And it seems that it initialize successfully the SDK.

Also, I want to attach this link as a reference https://github.com/juancarlosqr/adjust-issue ,  This is the same issue  I have been dealing with. Btw, I'm using React.

Kindly let me know if I am missing something? 

Thanks.

**Comment by uerceg** [comment]
Hi @sanjosedennis7593 

Can you initialize SDK in sandbox mode + set log level to verbose, make a test run and send over logs in here? Feel free to omit any information from logs which you might find sensitive.

**Comment by sanjosedennis7593** [comment]
On the initialization this is the logs

![image](https://user-images.githubusercontent.com/16043743/119991154-be940400-bffb-11eb-9460-b661114f32cf.png)

**Comment by YaroslavnaMatkova** [comment]
Hi @sanjosedennis7593

The SDK delays event tracking until `/session` request succeeded otherwise the server will decline the event because SDK hadn't started the session but tries to sent events. So the issue is why the session wasn't succeeded.

I've checked the repo you attached for reference and it seems the web tracking is disabled for the used app token.

Could you please share the response for `/session` request shown in Network tab of your browser developer tools?

**Comment by YaroslavnaMatkova** [comment]
Could you share server response message? It shown in human-readable form on Preview view of Network tab, for example:

![image](https://user-images.githubusercontent.com/20902231/120020868-fc405f00-bff2-11eb-8099-4e290a8b63b2.png)

**Comment by sanjosedennis7593** [comment]
Oh sorry, i didn't show that one. This is the response. The issue is because  tracking is disabled. Can you give me a walkthrough how to enable it? 

![image](https://user-images.githubusercontent.com/16043743/120055893-8debb300-c06b-11eb-9c4f-ea01f37f3db7.png)

**Comment by FrauJohansson** [comment]
Hi @sanjosedennis7593 You would need to contact your Adjust Account Manager or Customer Success Manager so that they can enable Web Tracking for you.

Thank you for your understanding.

**Comment by sanjosedennis7593** [comment]
Ok, thanks  for the help. Will reach out to them. :)
