### ISSUE TITLE
Error al iniciar sesion.

### ISSUE THREAD

**Issue by MarshallRdgz** [adjust/web_sdk#19]
Al momento de que se quiere iniciar sessión en adjust muestra este error

![image](https://user-images.githubusercontent.com/53185192/121588652-ca1ffb80-c9fb-11eb-9e9a-bdb05718ea11.png)

pero no es en todos los casos solo es en algunos especificos.
en la mayoria de los casos me responde correctamente.
![image](https://user-images.githubusercontent.com/53185192/121588850-04899880-c9fc-11eb-9166-d78498f4c745.png)

**Comment by mauro90015** [comment]
At the moment when you want to log into adjust it shows this error

![121588652-ca1ffb80-c9fb-11eb-9e9a-bdb05718ea11](https://user-images.githubusercontent.com/85886122/121906483-c7b9ec00-ccf0-11eb-8fa1-2e366c980e73.png)

It is not happening in all cases, it is only in some specific ones.
In most cases he answers me correctly.

![121588850-04899880-c9fc-11eb-9166-d78498f4c745](https://user-images.githubusercontent.com/85886122/121906523-cee0fa00-ccf0-11eb-8ca7-eb16cd25e936.png)

**Comment by YaroslavnaMatkova** [comment]
Hello @MarshallRdgz, @mauro90015!

This `ERR_BLOCKED_BY_CLIENT` message is generated by browser when it failed to send request to host. Most probably it's because of advertisement blocking software or your network configuration.

**Comment by uerceg** [comment]
@mauro90015 Any update on this one? Are you still facing this issue?

**Comment by uerceg** [comment]
If still needed, feel free to comment / reopen. Cheers.
