### ISSUE TITLE
web sdk does not work with SSR apps

### ISSUE THREAD

**Issue by adrienlo** [adjust/web_sdk#23]
Because of the references to `window`, the sdk doesn't work. Was this meant to work with SSR apps?

```
error - ReferenceError: window is not defined
    at eval (webpack-internal:///./pages/_app.jsx:54:1)
    at Module../pages/_app.jsx (/Users/Work/web/.next/server/pages/_app.js:139:1)
```

**Comment by YaroslavnaMatkova** [comment]
Hi @adrienlo, sorry for a pretty long delay.

Yes, Web SDK uses some clients-side Web APIs.
You could workaround this and import the SDK only when `window` is defined.

If it's applicable to your project you can combine this approach with [React Context](https://reactjs.org/docs/context.html):

```
import { createContext, useContext } from 'react';

const AdjustContext = createContext();

export function AdjustWrapper({ children }) {
  let AdjustSdk

  if (typeof window !== 'undefined') {
    AdjustSdk = require('@adjustcom/adjust-web-sdk')

    AdjustSdk.initSdk({
      appToken: "YOUR_APP_TOKEN",
      environment: "production", // or "sandbox"
      // ... other optional parameters if needed
    })
  }

  return (
    <AdjustContext.Provider value={AdjustSdk}>
      {children}
    </AdjustContext.Provider>
  );
}

export function useAdjustContext() {
  return useContext(AdjustContext);
}
```

Use this `AdjustWrapper` in top-level component of your app: 
``` 
import { AdjustWrapper } from '../libs/adjust'

export default function App() {
  return (
    <AdjustWrapper>
      {/* other components here */}
    </AdjustWrapper>
  )
}
```
and add `useAdjustContext` hook to get `AdjustSdk` when it's needed in components:
```
import { useAdjustContext } from '../libs/adjust'

export function TrackEventButton() {
  const adjustSdk = useAdjustContext()

  return (
    <button onClick={() => {
      adjustSdk.trackEvent({ eventToken: 'EVENT_TOKEN' })
    }}>Track event</button>
  )
}
```

Let me know if you still have questions

**Comment by AntoineBouquet** [comment]
I may found a solution : if I use the inline script directly on my index.html of my Angular project, I don't have build SSR compilation error.

```
<head>
  <script type="text/javascript">
      !function(t,a,e,r,s,l,d,n,o){t.Adjust=t.Adjust||{},t.Adjust_q=t.Adjust_q||[];for(var c=0;c<l.length;c++)d(t.Adjust,t.Adjust_q,l[c]);n=a.createElement("script"),o=a.getElementsByTagName("script")[0],n.async=!0,n.src="https://cdn.adjust.com/adjust-5.2.1.min.js",n.onload=function(){for(var a=0;a<t.Adjust_q.length;a++)t.Adjust[t.Adjust_q[a][0]].apply(t.Adjust,t.Adjust_q[a][1]);t.Adjust_q=[]},o.parentNode.insertBefore(n,o)}(window,document,0,0,0,["initSdk","trackEvent","addGlobalCallbackParameters","addGlobalPartnerParameters","removeGlobalCallbackParameter","removeGlobalPartnerParameter","clearGlobalCallbackParameters","clearGlobalPartnerParameters","switchToOfflineMode","switchBackToOnlineMode","stop","restart","gdprForgetMe","disableThirdPartySharing"],function(t,a,e){t[e]=function(){a.push([e,arguments])}});
    </script>
</head>

<body>
  [...]
  
  <script type="text/javascript">
    Adjust.initSdk({
      appToken: 'token',
      environment: 'sandbox',
    });
  </script>
</body>
```

**Comment by YaroslavnaMatkova** [comment]
Hey @AntoineBouquet,

I suggest to workaround this issue using dynamic import depending on platform:

```
import { PLATFORM_ID, Inject, Injectable } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

import type AdjustSDK from "@adjustcom/adjust-web-sdk";

@Injectable({ providedIn: 'root' })
export class AdjustService {
    private Adjust: typeof AdjustSDK | null = null;

    constructor(@Inject(PLATFORM_ID) private platformId: Object) { }

    async init() {
        if (isPlatformBrowser(this.platformId)) {
            this.Adjust = (await import("@adjustcom/adjust-web-sdk")).default;

            this.Adjust.initSdk({
                appToken: "YOUR_APP_TOKEN",
                environment: "sandbox",
                logLevel: "verbose"
            });
        }
    }

    trackEvent() {
        if (this.Adjust) {
            this.Adjust.trackEvent({ eventToken: "YOUR_EVENT_TOKEN" });
        }
    }
}

**Comment by uerceg** [comment]
In case there's still some assistance you need when it comes to this issue, feel free to comment / reopen. Cheers!

**Comment by yamatsum** [comment]
@YaroslavnaMatkova 

I initialized sdk with the following code
Then, the following message was displayed.
https://github.com/adjust/web_sdk/issues/23#issuecomment-920707406

```
[adjust-sdk] 2022-06-12T06:39:45.759Z ERROR: You already initiated your instance
```

Is there any solution?

**Comment by yamatsum** [comment]
As a workaround, this is the solution

```
export const AdjustProvider: FC = ({ children }) => {
  let Adjust;

  const [didInit, setDidInit] = useState(false);

  if (!didInit && typeof window !== "undefined") {
    Adjust = require("@adjustcom/adjust-web-sdk");

    AdjustSdk.initSdk({
      appToken: "YOUR_APP_TOKEN",
      environment: "production", // or "sandbox"
      // ... other optional parameters if needed
    })
    setDidInit(true);
  }

  return (
    <AdjustContext.Provider value={Adjust}>{children}</AdjustContext.Provider>
  );
};
```

**Comment by Darknessbeast** [comment]
Hi, I am trying to integrate the Web Sdk to my playcanvas game. but when I open it on Live Server I keep getting this error: **Failed to load resource: the server responded with a status of 400 (Bad Request)**
it seems this part of the adjust-latest.min.js is the problem: `n.send("GET" === i ? void 0 : c)`

the funny thing is when I just simply open the html file in my browser Adjust Sdk works perfectly.
here is my html code:

`<!doctype html>
<html>
<head>
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover' />
    <meta charset='utf-8'>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <link rel="manifest" href="manifest.json">
    <style></style>
    <title>Main Page</title>

    <script type="text/javascript">
        !function(t,a,e,r,s,l,d,n,o){t.Adjust=t.Adjust||{},t.Adjust_q=t.Adjust_q||[];for(var c=0;c<l.length;c++)d(t.Adjust,t.Adjust_q,l[c]);n=a.createElement("script"),o=a.getElementsByTagName("script")[0],n.async=!0,n.src="https://cdn.adjust.com/adjust-latest.min.js",n.onload=function(){for(var a=0;a<t.Adjust_q.length;a++)t.Adjust[t.Adjust_q[a][0]].apply(t.Adjust,t.Adjust_q[a][1]);t.Adjust_q=[]},o.parentNode.insertBefore(n,o)}(window,document,0,0,0,["initSdk","trackEvent","addGlobalCallbackParameters","addGlobalPartnerParameters","removeGlobalCallbackParameter","removeGlobalPartnerParameter","clearGlobalCallbackParameters","clearGlobalPartnerParameters","switchToOfflineMode","switchBackToOnlineMode","stop","restart","gdprForgetMe","disableThirdPartySharing"],function(t,a,e){t[e]=function(){a.push([e,arguments])}});
      </script>

    <script src="playcanvas-stable.min.js"></script>
    <script src="__settings__.js"></script>
</head>
<body>
    <script src="__start__.js"></script>
    <script src="__loading__.js"></script>

    <script type="text/javascript">

        Adjust.initSdk({
          appToken: [my own token], 
          environment: 'production', 

          logLevel: 'verbose', 
          logOutput: '#output',

        });

      </script>

</body>
</html>`

how can I fix this?
