### ISSUE TITLE
how to import 

### ISSUE THREAD

**Issue by coderzym** [adjust/web_sdk#26]
npm install @adjustcom/adjust-web-sdk --save

how to import ?

thank you

**Comment by AntoineBouquet** [comment]
Hi,

I think the answer is :

`import * as Adjust from '@adjustcom/adjust-web-sdk';`

and if you want to use method like `initSdk` :  
```
Adjust.default.initSdk({
         appToken: 'token',
         environment:  'production'
});
```

**Comment by coderzym** [comment]
> Hi,
> 
> I think the answer is :
> 
> `import * as Adjust from '@adjustcom/adjust-web-sdk';`
> 
> and if you want to use method like `initSdk` :
> 
> ```
> Adjust.default.initSdk({
>   appToken: 'token',
>   environment:  'production'
> });
> ```

I got it, thank you very much!

**Comment by YaroslavnaMatkova** [comment]
Hi @coderzym, @AntoineBouquet, thank you for reaching out to us and sorry for a slow response.

Please find an example below:
```
import Adjust from '@adjustcom/adjust-web-sdk';

Adjust.initSdk({
    appToken: 'your-app-token',
    environment: 'sandbox'
});

**Comment by YaroslavnaMatkova** [comment]
In case if help needed feel free to comment or reopen
