### ISSUE TITLE
An option to get attribution data instantly

### ISSUE THREAD

**Issue by Tbutnyakov** [adjust/web_sdk#27]
Hello!

We have an option to get user attribution data for IOS and Android SDK. 
But what about web SDK?
Can't see any info about that in docs,  only about attribution callback.
Example for Android SDK below:

![image](https://user-images.githubusercontent.com/3198162/145049118-298fd1f5-16ad-452c-af1a-9129876c7f18.png)

**Comment by uerceg** [comment]
Hi @Tbutnyakov 

Indeed, we still didn't add the attribution getter which mobile SDKs have into Web SDK. We will add it to our roadmap, makes sense to be out there. 👍

**Comment by Tbutnyakov** [comment]
Thanks, will wait!

**Comment by uerceg** [comment]
Hi @Tbutnyakov,

And sorry for a bit of delay on this one. We have released [Web SDK v5.3.0](https://github.com/adjust/web_sdk/releases/tag/v5.3.0) which has added this getter into publicly available API. Feel free to give it a shot and in case you encounter any issues, feel free to ping us.

Cheers!
