### ISSUE TITLE
Error "tracking disabled" after install Adjust SDK in VueJS

### ISSUE THREAD

**Issue by PVARS** [adjust/web_sdk#30]
I'm doing config Adjust SDK (https://github.com/adjust/web_sdk) with VueJS.

After installing the library at `npm install @adjustcom/adjust-web-sdk --save` and import into the project as follow:

**main.js:**

```
import Adjust from '@adjustcom/adjust-web-sdk';

Adjust.initSdk({
  appToken: MY_TOKEN,
  environment: 'sanbox',
  logLevel: 'verbose'
});
```

**Action in button:**

```
Adjust.trackEvent({
  eventToken: 'MY_TOKEN'
})
```

After the installation is completed there was an error:

`{error: "Attribution request failed (tracking disabled) (app_token:xxxxx) (platform:web)"}
`

**Comment by YaroslavnaMatkova** [comment]
Hi @PVARS,

You would need to contact your Adjust Account Manager or Customer Success Manager so that they can enable Web Tracking for you.

Thank you for your understanding.

**Comment by PVARS** [comment]
> Hi @PVARS,
> 
> You would need to contact your Adjust Account Manager or Customer Success Manager so that they can enable Web Tracking for you.
> 
> Thank you for your understanding.

My account is an admin role, where can I enable web tracking?

**Comment by YaroslavnaMatkova** [comment]
Unfortunately it's not possible to enable Web Tracking in the Dashboard, the only way is to contact your Adjust Account Manager or Customer Success Manager. 

Sorry for inconvenience and thank you for your understanding.
