### ISSUE TITLE
Get web_uuid standard function

### ISSUE THREAD

**Issue by 16francej** [adjust/web_sdk#31]
The react-native SDK has [helper functions](https://github.com/adjust/react_native_sdk#adjust-device-identifier) that make it straightforward to get the Adjust ID that has been set on a device. This is useful for server-to-server adjust events where the advertiser ID has to be passed from client to server before firing the event. 

The web SDK should also have these helper functions, especially given that web_uuid can be stored differently depending on the browser/platform in question. 

Is there a plan to support this in the near future?

**Comment by uerceg** [comment]
Hi @16francej,

Yes, getter for `web_uuid` is coming up in next Web SDK update. If not by end of this week, then next week release should be live. Will keep you posted.

**Comment by 16francej** [comment]
@uerceg Any updates?

**Comment by uerceg** [comment]
Hey @16francej,

Yes, sorry for a bit of delay. We have completed the feature, it's currently in review. Unfortunately, SDK update might not go live tomorrow, but definitely beginning of next week.

**Comment by 16francej** [comment]
@uerceg Wanted to check in on this, happy to work on a branch with you all if that would be possible

**Comment by uerceg** [comment]
Hey @16francej,

Sorry one more time and thanks for following up. We will have this release live later today. :) Will ping you in here once it's live.

**Comment by uerceg** [comment]
Hi @16francej,

We have released [Web SDK v5.3.0](https://github.com/adjust/web_sdk/releases/tag/v5.3.0) which has added this getter into publicly available API. Feel free to give it a shot and in case you encounter any issues, feel free to ping us.

Cheers!
