### ISSUE TITLE
How to make sure the web sdk is successfully initialized

### ISSUE THREAD

**Issue by zhengminhui** [adjust/web_sdk#32]
Hi team, I'm not sure if this is a dumb question or not. I'm integrating the web SDK in an SSR website. How can we check if the SDK is properly working after initiation before we launch to production?

Thank you.

**Comment by YaroslavnaMatkova** [comment]
Hi @zhengminhui 👋 

To check Web SDK integration you could set SDK log level to `verbose`  and inspect output in browser development console, and on Network tab of browser development tools you could check that the SDK sends its requests.

Also you could use [Testing Console](https://help.adjust.com/en/article/testing-console) in Adjust Dashboard to ensure the SDK works properly.

**Comment by uerceg** [comment]
In case there's still some assistance you need when it comes to this issue, feel free to comment / reopen. Cheers!
