### ISSUE TITLE
When cookies are blocked, Adjust breaks and prevents site to load

### ISSUE THREAD

**Issue by esmon** [adjust/web_sdk#46]
I'm importing Adjust with the script tag example and loading my project with cookies blocked is preventing the site to load and eventually crashes the tab. Here's is the error in console.

![Screen Shot 2022-10-24 at 6 52 59 PM](https://user-images.githubusercontent.com/2371561/197645561-81a5f8cc-7224-48f8-8552-2f2ddb948991.png)

**Comment by YaraMatkova** [comment]
Hi @esmon!
Thank you for your message.

Could you please share [verbose log](https://github.com/adjust/web_sdk#user-content-log-level)?
Could you tell what browser and what settings to block cookies do you use when you face this issue?

**Comment by esmon** [comment]
Hi @YaraMatkova,

The above screenshot is the only logs I can see... I'm using Chrome Version 106.0.5249.119 (Official Build) (x86_64) and I'm using Chrome Settings to block cookies. I'm aware that blocking cookies in this manner will break a lot of other services. I'm just wondering if there would be a more graceful way for Adjust SDK to handle this and not prevent my project from loading/tab timeout.

<img width="1270" alt="Screen Shot 2022-10-25 at 9 31 42 AM" src="https://user-images.githubusercontent.com/2371561/197787179-ca24ff9a-71ad-428f-bf40-86b5c0d992f3.png">

**Comment by YaraMatkova** [comment]
Hi @esmon!

Thank you for letting know about this issue.

The fix is in progress and it will be released in one of next SDK versions. Will keep you posted.

**Comment by esmon** [comment]
Thank you for the update @YaraMatkova

**Comment by YaraMatkova** [comment]
Hi @esmon, Web SDK v5.5.0 released, the issue should be fixed now.

Feel free to give it a shot and in case you face any issue or if you have any other question, feel free to comment / reopen.
