### ISSUE TITLE
Guidance Required for DMA Compliance with Adjust SDK

### ISSUE THREAD

**Issue by fhenri42** [adjust/web_sdk#56]
Hello,

I am currently integrating the Adjust SDK into my web application and aim to ensure compliance with the Digital Markets Act (DMA) as outlined in your article (https://help.adjust.com/fr/article/google-compliancy-with-the-dma). However, I'm encountering difficulties understanding how to correctly pass the new variables for DMA compliance:

```
eea=<boolean>
ad_personalization=<boolean>
npa=<boolean>
ad_user_data=<boolean>
```

Could you provide detailed guidance or examples on how to implement these variables within the SDK? Ensuring compliance is crucial for my application, and I would greatly appreciate any assistance or resources you can offer to help me understand and apply these requirements effectively.

Thank you very much for your support and the valuable resources you provide.

**Comment by uerceg** [comment]
Hello @fhenri42,

And thanks for the inquiry. I would encourage you to either ask this question directly to your dedicated account manager in case you have one or send this question and reference this ticket to support@adjust.com and you will be assisted with this topic by someone from our support team who is familiar with this topic on our end.

Cheers
