### ISSUE TITLE
session call internal issue

### ISSUE THREAD

**Issue by amplitudeblievin** [adjust/web_sdk#58]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

![image](https://github.com/user-attachments/assets/8f9ea90c-ea6c-4b28-830a-63e6f84a970d)

Here is my integration
```

         !(function (t, e, a, r, n, s, o, d, l, i, u) {
      (t.Adjust = t.Adjust || {}), (t.Adjust_q = t.Adjust_q || []);
      for (var c = 0; c < d.length; c++) l(t.Adjust, t.Adjust_q, d[c]);
      (i = e.createElement(a)),
         (u = e.getElementsByTagName(a)[0]),
         (i.async = !0),
         (i.src = "https://cdn.adjust.com/adjust-5.6.0.min.js"),
         (i.crossOrigin = "anonymous"),
         (i.integrity = s),
         (i.onload = function () {
            for (var e = 0; e < t.Adjust_q.length; e++)
               t.Adjust[t.Adjust_q[e][0]].apply(t.Adjust, t.Adjust_q[e][1]);
            t.Adjust_q = [];
         }),
         u.parentNode.insertBefore(i, u);
   })(
      window,
      document,
      "script",
      0,
      0,
      "sha384-BqbTn9xyk5DPznti1ZP8ksxKiOFhKufLBFWm5eNMCnZABFSG1eqQfcu5dsiZJHu5",
      0,
      [
         "initSdk",
         "getAttribution",
         "getWebUUID",
         "setReferrer",
         "trackEvent",
         "addGlobalCallbackParameters",
         "addGlobalPartnerParameters",
         "removeGlobalCallbackParameter",
         "removeGlobalPartnerParameter",
         "clearGlobalCallbackParameters",
         "clearGlobalPartnerParameters",
         "switchToOfflineMode",
         "switchBackToOnlineMode",
         "stop",
         "restart",
         "gdprForgetMe",
         "disableThirdPartySharing",
         "initSmartBanner",
         "showSmartBanner",
         "hideSmartBanner",
      ],
      function (t, e, a) {
         t[a] = function () {
            e.push([a, arguments]);
         };
      },
   );

        Adjust.initSdk({
            appToken: "apptoken",
            environment: "production",
            logLevel: "verbose",
        });
        
        Adjust.trackEvent({
            eventToken: "eventtoken",
        });
       
```

**Comment by YaraMatkova** [comment]
Hi @amplitudeblievin, thank you for getting in touch.

Your integration code looks correct.
Could you please also share an error message from server? It should be available on Network tab => Response in browser development tools.

**Comment by amplitudeblievin** [comment]
Hello @YaraMatkova 

I have this error:
{"error":"Session failed (failed to get app token)"}

I need to say when I give a try with S2S I have the exact same error

**Comment by amplitudeblievin** [comment]
But I do set correctly the app token, and I cross check already it was ok

**Comment by YaraMatkova** [comment]
Thank you for sharing the error message!

Unfortunately, it's not possible to say what is happening here without checking application or account details.
Could you please contact your Adjust Account Manager or Customer Success Manager to avoid sharing sensitive information here?

**Comment by amplitudeblievin** [comment]
Hey Yara,

I am on a demo plan.

I am working for Amplitude, which is a partner of Adjust, and I just needed project from Adjust so I can send data from Adjust to Amplitude and the opposite.

We are working on troubleshooting guide to assist our customer on that matter.

**Comment by YaraMatkova** [comment]
Hey @amplitudeblievin, thank you for letting know the details.

I suppose the reason of getting Server error is that you are on Demo plan. 
Could you please to reach out your point of contact in Adjust?

**Comment by amplitudeblievin** [comment]
Thank you very much Yara!

I will do!
