### ISSUE TITLE
Add ability to import SDK as a js module

### ISSUE THREAD

**Issue by leutsky** [adjust/web_sdk#6]
For example https://github.com/joomcode/adjust-web-sdk/commit/575f95eaafa0b77bd81964c8bc0f5a33945b327b

**Comment by uerceg** [comment]
Hi @ALeutsky 

Thanks for suggestion. We are actually planning to add support for this in next SDK update. If this fork works for you and does the trick for you until official release, awesome.

Next update we plan will be major one, work is currently in progress, so won't be out there super soon, but in there we plan to add support for this, CDN and NPM repo as well.

Cheers

**Comment by ALeutsky** [comment]
Hello @uerceg!
Good news
Can you tell me when you plan to release the next update?

**Comment by uerceg** [comment]
Not at this moment since roadmap can still suffer some changes on the fly so can't say anything for sure. Super roughly might be during Q3, but like said - might as well change in the meantime.

**Comment by uerceg** [comment]
This is actually now available. Feel free to check the updated SDK README. Cheers!
