### ISSUE TITLE
Unify arguments for error_cb

### ISSUE THREAD

**Issue by leutsky** [adjust/web_sdk#7]
The **error_cb** call with different number and types of arguments

https://github.com/adjust/web_sdk/blob/4a332435da75f352608e077974fbeced5bea4f2c/dist/adjust.js#L15
https://github.com/adjust/web_sdk/blob/4a332435da75f352608e077974fbeced5bea4f2c/dist/adjust.js#L21

**Comment by uerceg** [comment]
This functionality has been removed in our Web SDK v5.0.0.
